export type AppTab =
  | 'appointments'
  | 'calendar'
  | 'calculators'
  | 'controls'
  | 'dashboard'
  | 'export'
  | 'import'
  | 'medications'
  | 'pdf'
  | 'profile'
  | 'search'
  | 'settings'
  | 'timeline'
  | 'vaccines'
  | 'vitals';
